# Generated by Django 3.2.8 on 2021-11-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_mentor',
            field=models.BooleanField(default=False),
        ),
    ]
