# Generated by Django 3.2.8 on 2021-11-14 06:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_myuser_is_mentor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_uuid', models.UUIDField(default=uuid.uuid1, editable=False)),
                ('query_message', models.TextField()),
                ('mentor_response', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='date_of_birth',
        ),
    ]
