# Generated by Django 3.2.8 on 2021-11-14 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20211114_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='creation_timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='query',
            name='modify_timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='modified'),
        ),
        migrations.AlterModelTable(
            name='query',
            table='query',
        ),
    ]
